### ISSUE TITLE
EXC_BAD_ACCESS on iPhone Simulator 64-Bit

### ISSUE THREAD

**Issue by michaelforrest** [nubbel/SexyDates#1]
I started seeing crashes when calling things like `(7).days.ago` and `@(1).day`.

**Comment by nubbel** [comment]
Thanks for the heads up!
Apparently this happens because [tagged pointers](https://www.mikeash.com/pyblog/friday-qa-2013-09-27-arm64-and-you.html) are used for classes like NSNumber in 64-bit mode.
Up to now I have no idea how to fix or workaround it...

**Comment by devxoul** [comment]
I sent a pull request #2

**Comment by nubbel** [comment]
Fixed by #3
